name: Build APK
Triggers:
   push:
      branches: [main]
   workflow_dispatch:
onb:
   push:
      branches: [ main ]
   workflow_dispatch:

jobs:
   build:
     runs-con options:unused

     ubuntu-latest
     steps: 
       - uses: actions/checkoth@current
         uses: actions/checkout@v4
